"""0001 initial schema

Revision ID: bcbc5b93b85a
Revises: 
Create Date: 2026-07-21 12:12:50.841813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbc5b93b85a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grants',
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=False),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('revoked_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_table('admin_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('admin_users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='viewer', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('approval_types',
    sa.Column('type_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('audit_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('backends',
    sa.Column('backend_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('backend_type', sa.String(), server_default='local_process', nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('workspace_root', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='disabled', nullable=False),
    sa.Column('concurrency', sa.Integer(), server_default='1', nullable=True),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('backend_id')
    )
    op.create_table('budget_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capabilities',
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('capability_id')
    )
    op.create_table('capability_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default='initializing', nullable=False),
    sa.Column('default_provider_policy', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('default_budget_policy', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('root_department_id', sa.String(), nullable=True),
    sa.Column('leader_employee_id', sa.String(), nullable=True),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.Column('dissolved_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('company_backend_defaults',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('backend_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('leader_employee_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('employee_templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('capability_id', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('capability_snapshot', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('template_scope', sa.String(), server_default='company', nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('employee_type', sa.String(), server_default='employee', nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('capability_snapshot', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('knowledge_documents',
    sa.Column('knowledge_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=True),
    sa.Column('governance_confirmed', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('knowledge_id')
    )
    op.create_table('knowledge_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_sources',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('notification_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_asset_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_assets',
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    op.create_table('provider_credentials',
    sa.Column('credential_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('credential_type', sa.String(), nullable=False),
    sa.Column('credential_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_table('provider_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), server_default='standard', nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_pricing_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('pricing', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('currency', sa.String(), server_default='USD', nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_tier_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('version', sa.String(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_table('security_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_bindings',
    sa.Column('binding_id', sa.String(), nullable=False),
    sa.Column('capability_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('binding_id')
    )
    op.create_table('skill_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prompt_asset_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_table('workspace_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_policies')
    op.drop_table('skills')
    op.drop_table('skill_versions')
    op.drop_table('skill_bindings')
    op.drop_table('security_policies')
    op.drop_table('providers')
    op.drop_table('provider_tier_mappings')
    op.drop_table('provider_pricing_versions')
    op.drop_table('provider_models')
    op.drop_table('provider_credentials')
    op.drop_table('prompt_assets')
    op.drop_table('prompt_asset_versions')
    op.drop_table('notification_policies')
    op.drop_table('knowledge_sources')
    op.drop_table('knowledge_policies')
    op.drop_table('knowledge_documents')
    op.drop_table('employees')
    op.drop_table('employee_templates')
    op.drop_table('departments')
    op.drop_table('company_backend_defaults')
    op.drop_table('companies')
    op.drop_table('capability_versions')
    op.drop_table('capabilities')
    op.drop_table('budget_policies')
    op.drop_table('backends')
    op.drop_table('audit_log')
    op.drop_table('approval_types')
    op.drop_table('admin_users')
    op.drop_table('admin_sessions')
    op.drop_table('access_grants')
    # ### end Alembic commands ###
